version: '3'

tasks:
  default:
    desc: List available commands.
    cmds:
      - task --list
      - echo ""
      - echo First time? Run [ task build ] to build the project images.
    silent: true

  build:
    desc: Build the project images.
    cmds:
      - cd frontend && yarn install
      - echo ""
      - cd backend && yarn install
      - echo ""
      - docker-compose build
      - echo ""
      - echo "You are ready to start the project, run [ task start ] to start the project."
    silent: true

  start:
    desc: Start the project containers.
    cmds:
      - docker-compose up -d
      - echo ""
      - echo "All project containers are running:"
      - echo - The frontend is running on http://localhost:3000/.
      - echo - The frontend GraphQL playground is running on http://localhost:3000/___graphql.
      - echo - The backend is running on http://localhost:3333/.
    silent: true

  stop:
    desc: Stop the project containers.
    cmds:
      - docker-compose stop
      - echo ""
      - echo All project containers are stopped.
    silent: true

  test:
    desc: Run the project tests.
    cmds:
      - echo Starting frontend tests..
      - cd frontend && yarn test
    silent: true

  test-ui:
    desc: Open the Cypress UI and run the project tests.
    cmds:
      - echo Opening Cypress UI..
      - cd frontend && yarn test:ui
    silent: true

  lint:
    desc: Run the project codestyle check.
    cmds:
      - echo Starting frontend codestyle check..
      - docker-compose exec frontend sh -c "yarn lint"
    silent: true

  update:
    desc: Update all dependencies in root, frontend and backend folders.
    cmds:
      - docker-compose exec frontend sh -c "yarn upgrade-interactive --latest"
      - docker-compose exec backend sh -c "yarn upgrade-interactive --latest"

  reset:
    desc: Reset the project containers, volumes, local dependencies and cache files.
    cmds:
      - echo Removing all node_modules folders..
      - cd frontend && sudo rm -rf node_modules
      - cd backend && sudo rm -rf node_modules
      - echo All node_modules folders removed.
      - echo ""
      - echo Removing frontend cache folder..
      - docker-compose exec frontend sh -c "rm -rf .cache/ && rm -rf public/"
      - echo Cache folders removed.
      - docker-compose down -v
    silent: true