name: CI/CD
on: push
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: cypress-io/github-action@v4
      with:
        working-directory: frontend
        browser: chrome
        build: yarn build
        start: yarn serve --port 3000

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run frontend linter
      run: yarn lint:frontend
    - name: Run backend linter
      run: yarn lint:backend