name: CI/CD
on: push
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: firefox
          build: yarn build
          start: yarn serve --port 3000

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn lint
      - name: Build project & generate types
        run: yarn build
      - name: Run TypeScript Check
        run: yarn check-types

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: yarn install
      - name: Run TypeScript Check
        run: yarn check-types
      - name: Build Sanity Studio
        run: yarn build
