name: CI/CD
on: push
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          browser: firefox
          build: yarn build
          start: yarn serve --port 3000

  code-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install modules
        run: yarn install
      - name: Run Prettier
        run: yarn run prettier:check
      - name: Run ESLint
        run: yarn run lint
      - name: Build project & generate types
        run: yarn build
      - name: Run TypeScript Check
        run: tsc --noEmit

  sanity-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install modules
        run: yarn install
      - name: Build Sanity Studio
        run: yarn build
