name: CI/CD
on: push
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: frontend
          browser: firefox
          build: yarn build
          start: yarn serve --port 3000

  code-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install modules
        run: yarn install
      - name: Run ESLint
        run: yarn run lint
      - name: Build project & generate types
        run: yarn build
      - name: Run TypeScript Check
        run: tsc --noEmit
